# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'oomph' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for oomph
	pod 'Alamofire' 
	pod 'SwiftyJSON', '~>4.2.0'
	pod 'IQKeyboardManagerSwift'
	pod 'Kingfisher'
	pod 'MBProgressHUD'
	pod 'KMPlaceholderTextView'
	pod 'SideMenu'
end
